[package]
name = "ume_tauri"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
default = ["gui"]
gui = ["tauri", "tauri-build", "tokio"]

[dependencies]
tauri = { version = "1", optional = true, features = ["http-all"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["process"], optional = true }

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt"] }

[build-dependencies]
tauri-build = { version = "1", optional = true }
