#!/bin/sh
set -e
if command -v pwsh >/dev/null 2>&1; then
    pwsh -NoLogo -NoProfile -File scripts/export-winget.ps1
elif command -v powershell >/dev/null 2>&1; then
    powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File scripts/export-winget.ps1
else
    echo "PowerShell is not installed" >&2
    exit 1
fi

git add winget-packages.json
