repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: ["."]
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]
  - repo: local
    hooks:
      - id: update-plugin-registry
        name: Check plugin registry
        entry: python -m scripts.update_registry --check
        language: system
        pass_filenames: false
