version: "3.8"
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n
      - ./n8n/flows:/flows
    environment:
      - GENERIC_TIMEZONE=UTC
      - N8N_PERSONALIZATION_ENABLED=false

  nextcloud:
    image: nextcloud
    ports:
      - "8082:80"
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_USERNAME:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD:-password}

  mattermost:
    image: mattermost/mattermost-team-edition
    ports:
      - "8065:8065"
    volumes:
      - ./mattermost:/mattermost/data
    environment:
      - MATTERMOST_TOKEN=${MATTERMOST_TOKEN:-}
      - MATTERMOST_CHANNEL_ID=${MATTERMOST_CHANNEL_ID:-}

  romm:
    image: rommapp/romm
    ports:
      - "8080:80"
    volumes:
      - ./romm:/romm

  neko:
    image: m1k1o/neko:latest
    ports:
      - "8081:8080"

  api:
    image: python:3.11-slim
    working_dir: /app
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
