version: "3.8"
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n
      - ./n8n/flows:/flows
    environment:
      - GENERIC_TIMEZONE=UTC
      - N8N_PERSONALIZATION_ENABLED=false

