#!/usr/bin/env python3
"""Generate palette artifacts from metadata/palettes.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ANSI_ORDER = [
    "black",
    "red",
    "green",
    "yellow",
    "blue",
    "purple",
    "cyan",
    "white",
    "bright_black",
    "bright_red",
    "bright_green",
    "bright_yellow",
    "bright_blue",
    "bright_purple",
    "bright_cyan",
    "bright_white",
]

STARSHIP_HEADER = """# AUTO-GENERATED by scripts/helpers/generate_palette_artifacts.py\nadd_newline = false\npalette = \"{default_palette}\"\nformat = \"{format}\"\n\n"""

STARSHIP_MODULES = r"""
[directory]
style = "fg:bright_purple"
truncation_length = 4
truncate_to_repo = false

[git_branch]
symbol = " "
style = "fg:purple"

[git_status]
style = "fg:bright_purple"
format = '([\[$all_status$ahead_behind\]]($style) )'

[python]
symbol = " "
format = '[$symbol($virtualenv )]($style)'
style = "fg:green"

[kubernetes]
symbol = "☸ "
format = '[$symbol$context( \($namespace\))]($style) '
style = "fg:cyan"
disabled = false

[aws]
symbol = "󰸏 "
format = '[$symbol$profile( \($region\))]($style) '
style = "fg:yellow"

[time]
disabled = false
format = "[$time]($style) "
style = "fg:purple"

[status]
disabled = false
format = '[$symbol$status]($style) '
style = "fg:red"

[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[package]
disabled = true
""".lstrip()


def to_scheme_name(palette_name: str) -> str:
    return palette_name.replace("-", " ").title()


def json_dump(data: object) -> str:
    return json.dumps(data, indent=2) + "\n"


def update_file(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return False
    if check:
        raise SystemExit(f"Drift detected in {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def render_palette_toml(name: str, ansi: dict[str, str]) -> str:
    lines = [f"[{name}]"]
    for key in ANSI_ORDER:
        lines.append(f'{key} = "{ansi[key]}"')
    return "\n".join(lines) + "\n"


def render_starship(config: dict[str, object]) -> str:
    default_name = config["default_palette"]
    fmt = config["starship"]["format"]
    chunks = [STARSHIP_HEADER.format(default_palette=default_name, format=fmt)]
    for name, palette in config["palettes"].items():
        chunks.append(f"[palettes.{name}]\n")
        for key in ANSI_ORDER:
            chunks.append(f'{key} = "{palette["ansi"][key]}"\n')
        chunks.append("\n")
    chunks.append(STARSHIP_MODULES)
    return "".join(chunks)


def render_tmux(default_palette: dict[str, dict[str, str]]) -> str:
    ansi = default_palette["ansi"]
    return (
        "# AUTO-GENERATED by scripts/helpers/generate_palette_artifacts.py\n"
        f"set -g status-style \"bg={ansi['black']},fg={ansi['white']}\"\n"
        "set -g status-left-length 40\n"
        "set -g status-right-length 80\n"
        f"set -g status-left \"#[fg={ansi['black']},bg={ansi['purple']},bold] 󰆍 #S #[default]\"\n"
        f"set -g status-right \"#[fg={ansi['cyan']}] %Y-%m-%d #[fg={ansi['green']}]%H:%M #[default]\"\n"
        f"set -g pane-border-style \"fg={ansi['bright_black']}\"\n"
        f"set -g pane-active-border-style \"fg={ansi['blue']}\"\n"
        f"set -g message-style \"bg={ansi['purple']},fg={ansi['black']}\"\n"
    )


def render_nvim_palette(default_palette: dict[str, dict[str, str]]) -> str:
    ansi = default_palette["ansi"]
    return (
        "-- AUTO-GENERATED by scripts/helpers/generate_palette_artifacts.py\n"
        "return {\n"
        f"  bg = \"{ansi['black']}\",\n"
        f"  fg = \"{ansi['white']}\",\n"
        f"  gray = \"{ansi['bright_black']}\",\n"
        f"  pink = \"{ansi['red']}\",\n"
        f"  green = \"{ansi['green']}\",\n"
        f"  yellow = \"{ansi['yellow']}\",\n"
        f"  blue = \"{ansi['blue']}\",\n"
        f"  purple = \"{ansi['purple']}\",\n"
        f"  cyan = \"{ansi['cyan']}\",\n"
        f"  magenta = \"{ansi['bright_purple']}\",\n"
        f"  white = \"{ansi['bright_white']}\",\n"
        "  bg_alt = \"#121212\",\n"
        "  bg_select = \"#1a1a1a\",\n"
        "}\n"
    )


def render_terminal_defaults(default_palette: dict[str, dict[str, str]], font: str = "CaskaydiaCove Nerd Font", size: str = "13") -> str:
    ansi = default_palette["ansi"]
    ui = default_palette["ui"]
    lines = [
        "# AUTO-GENERATED by scripts/helpers/generate_palette_artifacts.py",
        "# Host overlays can override these values from ~/.config/tino/host-overrides.sh.",
        "",
        f'export TINO_TERMINAL_FONT_FAMILY="{font}"',
        f'export TINO_TERMINAL_FONT_SIZE="{size}"',
        "",
        'export TINO_TERMINAL_OPACITY="0.92"',
        'export TINO_TERMINAL_FPS="120"',
        'export TINO_TERMINAL_EFFECTS="on"',
        "",
        f'export TINO_TERMINAL_BACKGROUND="{ui["background"]}"',
        f'export TINO_TERMINAL_FOREGROUND="{ui["foreground"]}"',
        f'export TINO_TERMINAL_CURSOR="{ui["cursor"]}"',
        f'export TINO_TERMINAL_SELECTION="{ui["selection"]}"',
        "",
    ]
    for idx, key in enumerate(ANSI_ORDER):
        lines.append(f'export TINO_TERMINAL_COLOR_{idx}="{ansi[key]}"')
    return "\n".join(lines) + "\n"


def render_windows_schemes(config: dict[str, object]) -> list[dict[str, str]]:
    schemes: list[dict[str, str]] = []
    for name, palette in config["palettes"].items():
        ansi = palette["ansi"]
        ui = palette["ui"]
        schemes.append(
            {
                "name": to_scheme_name(name),
                "black": ansi["black"],
                "red": ansi["red"],
                "green": ansi["green"],
                "yellow": ansi["yellow"],
                "blue": ansi["blue"],
                "purple": ansi["purple"],
                "cyan": ansi["cyan"],
                "white": ansi["white"],
                "brightBlack": ansi["bright_black"],
                "brightRed": ansi["bright_red"],
                "brightGreen": ansi["bright_green"],
                "brightYellow": ansi["bright_yellow"],
                "brightBlue": ansi["bright_blue"],
                "brightPurple": ansi["bright_purple"],
                "brightCyan": ansi["bright_cyan"],
                "brightWhite": ansi["bright_white"],
                "background": ui["background"],
                "foreground": ui["foreground"],
                "cursorColor": ui["cursor"],
                "selectionBackground": ui["selection"],
            }
        )
    return schemes


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files would change")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    config = json.loads((repo_root / "metadata" / "palettes.json").read_text(encoding="utf-8"))
    default_name = config["default_palette"]
    default_palette = config["palettes"][default_name]

    targets: dict[Path, str] = {}
    for name, palette in config["palettes"].items():
        targets[repo_root / "palettes" / f"{name}.toml"] = render_palette_toml(name, palette["ansi"])

    targets[repo_root / "dotfiles" / "shell" / ".config" / "starship.toml"] = render_starship(config)
    targets[repo_root / "dotfiles" / "tmux" / ".tmux.palette.conf"] = render_tmux(default_palette)
    targets[repo_root / "dotfiles" / "nvim" / ".config" / "nvim" / "lua" / "config" / "palette.lua"] = render_nvim_palette(default_palette)
    targets[repo_root / "dotfiles" / "terminal" / ".config" / "tino" / "terminal-defaults.sh"] = render_terminal_defaults(default_palette)

    schemes = render_windows_schemes(config)
    default_scheme = to_scheme_name(default_name)

    base_path = repo_root / "windows-terminal" / "settings.base.json"
    base = json.loads(base_path.read_text(encoding="utf-8"))
    base.setdefault("profiles", {}).setdefault("defaults", {})["colorScheme"] = default_scheme
    for profile in base.setdefault("profiles", {}).get("list", []):
        if not profile.get("colorScheme"):
            profile["colorScheme"] = default_scheme
    base["schemes"] = schemes
    targets[base_path] = json_dump(base)

    overrides = {
        "profiles": {
            "defaults": {
                "font": {"face": "CaskaydiaCove Nerd Font", "size": 13},
                "acrylicOpacity": 0.92,
                "colorScheme": default_scheme,
            }
        },
        "schemes": schemes,
    }
    targets[repo_root / "windows-terminal" / "terminal-profile-overrides.json"] = json_dump(overrides)

    changed = False
    for path, content in targets.items():
        changed = update_file(path, content, args.check) or changed

    if args.check:
        print("Palette artifacts are synchronized.")
    elif changed:
        print("Updated palette artifacts.")
    else:
        print("Palette artifacts already up to date.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
