-- AUTO-GENERATED by scripts/helpers/generate_palette_artifacts.py
return {
  bg = "#000000",
  fg = "#f2f2f2",
  gray = "#666666",
  pink = "#ff66c4",
  green = "#b2ff59",
  yellow = "#ffff66",
  blue = "#66b2ff",
  purple = "#845CFF",
  cyan = "#66fff2",
  magenta = "#FC17DA",
  white = "#ffffff",
  bg_alt = "#121212",
  bg_select = "#1a1a1a",
}
