#!/usr/bin/env python3
"""Interactively execute shell commands generated by ``ai_exec.plan``.

Prompts before each step unless ``--yes``/``--confirm`` are supplied."""


from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Callable, List, Optional, Sequence

from scripts import ai_exec
from llm.backends import initialize
from scripts.cli_common import (
    send_notification,
    build_analytics_parser,
    execute_steps,
)
from scripts import cli_actions
from telemetry import analytics_default

REPO_ROOT = Path(__file__).resolve().parent.parent

initialize()


def run_recipe(
    name: str,
    goal: str,
    steps_or_callable: Sequence[str] | Callable[[str], Sequence[str]],
    *,
    log_path: Path,
    analytics: bool = False,
    nats_url: str | None = None,
) -> int:
    """Execute a recipe given steps or a callable and record an event."""
    return cli_actions.run_recipe(
        name,
        goal,
        steps_or_callable,
        log_path=log_path,
        analytics=analytics,
        nats_url=nats_url,
    )


def main(argv: Optional[List[str]] = None) -> int:
    analytics_group = build_analytics_parser()
    parser = argparse.ArgumentParser(description=__doc__, parents=[analytics_group])
    parser.add_argument("goal", help="High level description of the task")
    parser.add_argument("--config")
    parser.add_argument("--notify", action="store_true", help="Send notification when done")
    parser.add_argument(
        "--log",
        type=Path,
        default=REPO_ROOT / "ai_do.log",
        help="Log file path (default: %(default)s)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print commands without executing",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Run without interactive prompts for non-risky commands",
    )
    parser.add_argument(
        "--confirm",
        action="store_true",
        help="Also run commands tagged [risk:*] without prompting",
    )
    args = parser.parse_args(argv)

    analytics = getattr(args, "analytics", analytics_default())
    cfg_path = Path(args.config) if args.config else None
    steps = ai_exec.plan(args.goal, config_path=cfg_path, analytics=analytics)
    dry_log: list[str] = []
    execute_steps(steps, log_path=args.log, dry_run=True, dry_run_log=dry_log)
    risk_present = any("[risk:" in s.command for s in steps)
    if args.dry_run:
        return 0
    if risk_present and not args.confirm:
        print("Risky commands present. Re-run with --confirm to execute.", file=sys.stderr)
        return 1
    exit_code = cli_actions.run_steps(
        "ai-do",
        steps,
        log_path=args.log,
        analytics=analytics,
        payload={
            "goal": args.goal,
            "model_source": "remote" if ai_exec.last_model_remote() else "local",
        },
        duration_key="duration_ms",
        nats_url=args.nats_url if hasattr(args, "nats_url") else None,
        assume_yes=args.yes,
        confirm=args.confirm,
        dry_run_log=dry_log,
    )
    if args.notify:
        if exit_code == 0:
            send_notification("ai-do completed with exit code 0")
        else:
            send_notification(f"ai-do failed with exit code {exit_code}")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
