[blacklight]
black = "#000000"
red = "#ff66c4"
green = "#b2ff59"
yellow = "#ffff66"
blue = "#66b2ff"
purple = "#845CFF"
cyan = "#66fff2"
white = "#f2f2f2"
bright_black = "#666666"
bright_red = "#ff66c4"
bright_green = "#b2ff59"
bright_yellow = "#ffff66"
bright_blue = "#66b2ff"
bright_purple = "#FC17DA"
bright_cyan = "#66fff2"
bright_white = "#ffffff"
