[dracula]
black = "#21222C"
red = "#FF5555"
green = "#50FA7B"
yellow = "#F1FA8C"
blue = "#BD93F9"
purple = "#FF79C6"
cyan = "#8BE9FD"
white = "#F8F8F2"
bright_black = "#6272A4"
bright_red = "#FF6E6E"
bright_green = "#69FF94"
bright_yellow = "#FFFFA5"
bright_blue = "#D6ACFF"
bright_purple = "#FF92DF"
bright_cyan = "#A4FFFF"
bright_white = "#FFFFFF"
