name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test]'
      - name: Run ruff
        run: ruff check .
      - name: Run mypy
        run: mypy --install-types --non-interactive
      - name: Install runtime requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -n auto

  extras-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies with extras
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test,lmql,guidance]' textual
      - name: Install runtime requirements
        run: pip install -r requirements.txt
      - name: Run tests with extras
        run: pytest -n auto

