name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        # Install Python packages for tests and JS packages for linting
        run: |
          python -m pip install --upgrade pip
          pip install -e . -r requirements.txt
          pip install mypy
          npm ci
      - name: Run ruff
        run: ruff check .

      - name: Run mypy
        run: mypy llm scripts

      - name: Invoke ai-plan
        run: ai-plan --help

      - name: Run tests
        run: pytest -n auto
      - name: Run backend/UI tests
        run: pytest -n auto tests/test_langchain_backend.py tests/test_openrouter_backend.py
      - name: Run smoke test
        run: pytest -n auto tests/test_smoke_test.py
      - name: Run lint
        run: npm run lint
      - name: Validate winget packages
        run: python scripts/validate_winget.py

  test-windows:
    name: Test (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        # Install Python packages for tests and JS packages for linting
        run: |
          python -m pip install --upgrade pip
          pip install -e . -r requirements.txt
          pip install mypy
          npm ci
      - name: Run ruff
        run: ruff check .

      - name: Run mypy
        run: mypy llm scripts

      - name: Invoke ai-plan
        run: ai-plan --help

      - name: Run tests
        run: pytest -n auto
      - name: Run backend/UI tests
        run: pytest -n auto tests/test_langchain_backend.py tests/test_openrouter_backend.py
      - name: Run smoke test
        run: pytest -n auto tests/test_smoke_test.py
      - name: Run lint
        run: npm run lint
      - name: Validate winget packages
        run: python scripts/validate_winget.py
