name: Link Check

on:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: --no-progress --verbose './**/*.md' './metadata/sources.json'
          fail: true
